import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    useColorModeValue,
    Heading,
    Text,
    Stack,
    Icon,
    Container,
    Image,
    Flex,
    Button,
    Grid,
    useBreakpointValue,
    createIcon,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router'
  import Angebot from '../../componenets/Angebot';

const Jura = ({ index, name, url , imageUrl }: Jura) => {

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter(); 
  
  return (
    <div>
       <Head>
        <title>Jura Kaffeevollautomaten || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb 
        ml={20} 
        mt={10}
        fontWeight='medium' fontSize='sm'>
        <BreadcrumbItem>
        <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
        </BreadcrumbItem>

       <BreadcrumbItem isCurrentPage >
       <BreadcrumbLink href={'/mashcineCategory/jura'}>Jura Kaffeevollautomaten </BreadcrumbLink>
       </BreadcrumbItem>

       </Breadcrumb>


       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Jura Kaffeevollautomaten
       </Text>

      <Center 
      py={12}
      pr={{ base: -16,  lg: 0 }} 
      mx={{ base: 16,  lg: 0 }}        
      >
      <Grid
          
          mb={{ base: 10,  lg: 20 }}
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={14} w={{ base: '100%', md: '80%', lg: '80%' }}
          >


     {JURA_ITEMS.map((jura) => (

      <Box
        key={jura.index}
        role={'group'}
        p={6}
        maxW={'330px'} 
        w={'full'} 
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={jura.imageUrl}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            {jura.brand}
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          {jura.name}
          </Heading>
          <Button 
           onClick={async () => { 
            router.push(jura.url);
  
            }}
          colorScheme='green'>Mehr Info </Button>
        </Stack>
      </Box>


  ))}

  
</Grid> 
    </Center>


    <Angebot/>


      <Center>
        <Stack
        my={{ base: 10, md: 20, lg: 20 }}
        mx={{ base: 10, md: 20, lg: 20 }}
       direction={{ base: 'column', md: 'row' }}>
      <Flex 
       p={{ base: 2,  lg: 8 }}   
       flex={1} 
       align={'center'} 
       justify={'center'}>
        <Stack spacing={6} w={'full'} maxW={'lg'}>
          <Heading 
          textAlign={'center'}
          fontSize={{ base: '2xl', md: '4xl', lg: '5xl' }}>
            <Text
              as={'span'}
              position={'relative'}
              
              _after={{
                content: "''",
                width: 'full',
                // eslint-disable-next-line react-hooks/rules-of-hooks
                height: useBreakpointValue({ base: '20%', md: '30%' }),
                position: 'absolute',
                bottom: 1,
                left: 0,
                bg: 'green.400',
                zIndex: -1,
              }}>
              Kaffee-Service Berlin Peter Ganss GmbH
            </Text>
            <br />{' '}
            <Text color={'green.400'} as={'span'}>
            ist Ihr zertifizierter Jura-Partner für Berlin
            </Text>{' '}
          </Heading>
          <Text 
          textAlign={'center'}
          fontSize={{ base: 'md', lg: 'lg' }} color={'gray.500'}>
          Bei uns sind Sie in guten Händen in allen Themen rund um Jura Professional Kaffeevollautomaten. Mit Rat und Tat stehen wir Ihnen zur
           Seite von der Kaufberatung über Einweisung bis hin zur Wartung und Pflege für Ihre optimale Kaffeeversorgung. Unsere Techniker besuchen
            regelmäßigen Schulungen bei Jura und unsere Werkstatt erzielt regelmäßig die Bestnote für ausgezeichneten Service und Qualität.
          </Text>
           
        </Stack>
      </Flex>
      <Flex flex={1}>
        <Image
          alt={'Login Image'}
          objectFit={'cover'}
          src={ '/jura/jura.jpg'}
        />
      </Flex>
    </Stack>
    
    </Center>

    </div>
  )
}





interface Jura {
    index?: string;
    children?: Array<Jura>;
    name?: string;
    brand?: string;
    url?: string;
    imageUrl?: string;
  }
  
  const JURA_ITEMS: Array<Jura> = [

     
    {
      index: '1',  
      name: 'Giga X3',  
      brand: 'Jura',
      url: '/maschine/jura/x3',
      imageUrl: '/jura/x3/1.jpg',
       
    },
    {
      index: '2',  
      name: 'Giga X3c',  
      brand: 'Jura',
      url: '/maschine/jura/x3',
      imageUrl: '/jura/x3c/1.jpg',
        
    },
    {
      index: '3', 
      name: 'Giga X8',  
      brand: 'Jura',
      url: '/maschine/jura/x3',
      imageUrl: '/jura/x8/1.jpg',
       
    },
    {
      index: '4', 
      name: 'Giga X8c',  
      brand: 'Jura',
      url: '/maschine/jura/x3',
      imageUrl: '/jura/x8c/1.jpg',
       
    },
    {
        index: '5', 
        name: 'Giga X6 ',  
        brand: 'Jura',
        url: '/maschine/jura/x3',
        imageUrl: '/jura/x6/1.jpg',
         
      },
      {
        index: '6', 
        name: 'Giga X10 ',  
        brand: 'Jura',
        url: '/maschine/jura/x3',
        imageUrl: '/jura/x10/1.jpg',
         
      },
      {
        index: '7', 
        name: 'Giga WE6 ',  
        brand: 'Jura',
        url: '/maschine/jura/x3',
        imageUrl: '/jura/we6/1.png',
         
      },
      {
        index: '8', 
        name: 'Giga WE8 ',  
        brand: 'Jura',
        url: '/maschine/jura/x3',
        imageUrl: '/jura/we8/1.png',
         
      },
    
  ];

export default Jura