import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    useColorModeValue,
    Heading,
    Text,
    Stack,
    Image,
    Button,
    Grid,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router'

const jura = () => {

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter(); 

  
  return (
    <div>
        <Head>
        <title>Jura Kaffeevollautomaten || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb 
        ml={20} 
        mt={10}
        fontWeight='medium' fontSize='sm'>
        <BreadcrumbItem>
        <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
        </BreadcrumbItem>

       <BreadcrumbItem isCurrentPage >
       <BreadcrumbLink href={'/mashcineCategory/jura'}>Jura Kaffeevollautomaten </BreadcrumbLink>
       </BreadcrumbItem>

       </Breadcrumb>


       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Jura Kaffeevollautomaten
       </Text>

      <Center py={12}  >
      <Grid
          
          mb={{ base: 10,  lg: 20 }}
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={14} w={{ base: '90%', md: '80%', lg: '80%' }}
          >

      <Box
        role={'group'}
        p={6}
        maxW={'330px'} 
        w={'full'} 
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/x3/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga X3 
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/x3c/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga X3c
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/x8/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga X8
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/x8c/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga X8c
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>


      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/x6/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga X6
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/x10/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga X10
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/we6/1.png'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga WE6
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/jura/we8/1.png'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            Jura
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Giga WE8
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>


      </Grid> 
    </Center>
    </div>
  )
}

export default jura