import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    useColorModeValue,
    Heading,
    Text,
    Stack,
    Image,
    Button,
    Grid,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router'

const Rex = ({ index, name, url , imageUrl }: Rex) => {

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter(); 
  
  return (
    <div>
       <Head>
        <title>Rex Royal Kaffeevollautomaten || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb 
        ml={20} 
        mt={10}
        fontWeight='medium' fontSize='sm'>
        <BreadcrumbItem>
        <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
        </BreadcrumbItem>

       <BreadcrumbItem isCurrentPage >
       <BreadcrumbLink href={'/mashcineCategory/jura'}>Rex Royal Kaffeevollautomaten </BreadcrumbLink>
       </BreadcrumbItem>

       </Breadcrumb>


       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Rex Royal Kaffeevollautomaten
       </Text>

      <Center py={12}  >
      <Grid
          
          mb={{ base: 10,  lg: 20 }}
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={14} w={{ base: '90%', md: '80%', lg: '80%' }}
          >


     {REX_ITEMS.map((rex) => (

      <Box
        key={rex.index}
        role={'group'}
        p={6}
        maxW={'330px'} 
        w={'full'} 
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={rex.imageUrl}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            {rex.brand}
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          {rex.name}
          </Heading>
          <Button 
           onClick={async () => { 
            router.push(rex.url);
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>


  ))}

  
</Grid> 
</Center>

    </div>
  )
}

interface Rex {
    index?: string;
    children?: Array<Rex>;
    name?: string;
    brand?: string;
    url?: string;
    imageUrl?: string;
  }
  
  const REX_ITEMS: Array<Rex> = [

     
    {
      index: '1',  
      name: 'S2',  
      brand: 'Rex Royal',
      url: '/',
      imageUrl: '/rex/s2/1.jpg',
       
    },
    {
      index: '2',  
      name: 'S300',  
      brand: 'Rex Royal',
      url: '/',
      imageUrl: '/rex/s300/1.jpg',
        
    },
    {
      index: '3', 
      name: 'S500',  
      brand: 'Rex Royal',
      url: '/',
      imageUrl: '/rex/s500/1.jpg',
       
    },
    
    
  ];

export default Rex