import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    useColorModeValue,
    Heading,
    Text,
    Stack,
    Image,
    Button,
    Grid,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router'

const jura = () => {

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const router = useRouter(); 

    
  return (
    <div>
        <Head>
        <title>Table Tops || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb 
        ml={20} 
        mt={10}
        fontWeight='medium' fontSize='sm'>
        <BreadcrumbItem>
        <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
        </BreadcrumbItem>

       <BreadcrumbItem isCurrentPage >
       <BreadcrumbLink href={'/mashcineCategory/jura'}>Table Tops</BreadcrumbLink>
       </BreadcrumbItem>

       </Breadcrumb>


       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Table Tops
       </Text>

      <Center py={12}  >
      <Grid
          
          mb={{ base: 10,  lg: 20 }}
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={14} w={{ base: '90%', md: '80%', lg: '80%' }}
          >

      <Box
        role={'group'}
        p={6}
        maxW={'330px'} 
        w={'full'} 
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/tabletop/ic/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
          laRhea
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Business Line iC 
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/tabletop/gpb/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
          laRhea
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Business Line Grande PB 
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/tabletop/grande/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
          laRhea
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          V+ Grande
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/tabletop/vho/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
          laRhea
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          V+ Grande Premium  
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>


      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/tabletop/2vho/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
          laRhea V+ Grande
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
           Premium 2VHO
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

      <Box
        role={'group'}
        p={6}
        maxW={'330px'}
        w={'full'}
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={'/tabletop/pb/1.jpg'}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
          laRhea

          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          Caffé europa PB
          </Heading>
          <Button 
           onClick={async () => { 
            router.push('/');
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>

     

      </Grid> 
    </Center>
    </div>
  )
}

export default jura