import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    useColorModeValue,
    Heading,
    Text,
    Stack,
    Image,
    Button,
    Grid,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router'

const TableTop = ({ index, name, url , imageUrl }: TableTop) => {

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter(); 
  
  return (
    <div>
       <Head>
        <title>Table Tops || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb 
        ml={20} 
        mt={10}
        fontWeight='medium' fontSize='sm'>
        <BreadcrumbItem>
        <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
        </BreadcrumbItem>

       <BreadcrumbItem isCurrentPage >
       <BreadcrumbLink href={'/mashcineCategory/jura'}>Table Tops </BreadcrumbLink>
       </BreadcrumbItem>

       </Breadcrumb>


       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Table Tops
       </Text>

      <Center py={12}  >
      <Grid
          
          mb={{ base: 10,  lg: 20 }}
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={14} w={{ base: '90%', md: '80%', lg: '80%' }}
          >


     {TABLETOP_ITEMS.map((tabletop) => (

      <Box
        key={tabletop.index}
        role={'group'}
        p={6}
        maxW={'330px'} 
        w={'full'} 
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={tabletop.imageUrl}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            {tabletop.brand}
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          {tabletop.name}
          </Heading>
          <Button 
           onClick={async () => { 
            router.push(tabletop.url);
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>


  ))}

  
</Grid> 
    </Center>

    </div>
  )
}

interface TableTop {
    index?: string;
    children?: Array<TableTop>;
    name?: string;
    brand?: string;
    url?: string;
    imageUrl?: string;
  }
  
  const TABLETOP_ITEMS: Array<TableTop> = [

     
    {
      index: '1',  
      name: 'Business Line iC ',  
      brand: 'laRhea',
      url: '/',
      imageUrl: '/tabletop/ic/1.jpg',
       
    },
    {
      index: '2',  
      name: 'Business Line Grande PB',  
      brand: 'laRhea',
      url: '/',
      imageUrl: '/tabletop/gpb/1.jpg',
        
    },
    {
      index: '3', 
      name: 'V+ Grande',  
      brand: 'laRhea',
      url: '/',
      imageUrl: '/tabletop/grande/1.jpg',
       
    },
    {
      index: '4', 
      name: 'V+ Grande Premium',  
      brand: 'laRhea',
      url: '/',
      imageUrl: '/tabletop/vho/1.jpg',
       
    },
    {
        index: '5', 
        name: 'Premium 2VHO',  
        brand: 'laRhea V+ Grande',
        url: '/',
        imageUrl: '/tabletop/2vho/1.jpg',
         
    },
    {
        index: '6', 
        name: 'Caffé europa PB',  
        brand: 'laRhea',
        url: '/',
        imageUrl: '/tabletop/pb/1.jpg',
         
    },  
  ];

export default TableTop