import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    useColorModeValue,
    Heading,
    Text,
    Stack,
    Image,
    Button,
    Grid,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router'

const wasser = ({ index, name, url , imageUrl }: Wasserspender) => {

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter(); 
  
  return (
    <div>
       <Head>
        <title>Wasserspender || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb 
        ml={20} 
        mt={10}
        fontWeight='medium' fontSize='sm'>
        <BreadcrumbItem>
        <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
        </BreadcrumbItem>

       <BreadcrumbItem isCurrentPage >
       <BreadcrumbLink href={'/mashcineCategory/jura'}>Wasserspender </BreadcrumbLink>
       </BreadcrumbItem>

       </Breadcrumb>


       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Wasserspender
       </Text>

      <Center py={12}  >
      <Grid
          
          mb={{ base: 10,  lg: 20 }}
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={14} w={{ base: '90%', md: '80%', lg: '80%' }}
          >


     {WASSER_ITEMS.map((wasser) => (

      <Box
        key={wasser.index}
        role={'group'}
        p={6}
        maxW={'330px'} 
        w={'full'} 
        // eslint-disable-next-line react-hooks/rules-of-hooks
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        rounded={'lg'}
        pos={'relative'}
        zIndex={1}>
        <Box
          rounded={'lg'} 
          pos={'relative'}
          height={'230px'}
           >
          <Image
            alt='jura'
            rounded={'lg'}
            height={230}
            width={282}
            objectFit={'contain'}
            src={wasser.imageUrl}
          />
        </Box>
        <Stack pt={10} align={'center'}>
          <Text color={'gray.500'} fontSize={'sm'} textTransform={'uppercase'}>
            {wasser.brand}
          </Text>
          <Heading fontSize={'2xl'} fontFamily={'body'} fontWeight={500}>
          {wasser.name}
          </Heading>
          <Button 
           onClick={async () => { 
            router.push(wasser.url);
  
            }}
          colorScheme='blue'>Mehr Info </Button>
        </Stack>
      </Box>


  ))}

  
</Grid> 
    </Center>

    </div>
  )
}

interface Wasserspender {
    index?: string;
    children?: Array<Wasserspender>;
    name?: string;
    brand?: string;
    url?: string;
    imageUrl?: string;
  }
  
  const WASSER_ITEMS: Array<Wasserspender> = [

     
    {
      index: '1',  
      name: 'VIVREAU Extra 50',  
      brand: 'BRITA',
      url: '/',
      imageUrl: '/wasser/ww.png',
       
    },
    {
      index: '2',  
      name: 'VIVREAU ViTap',  
      brand: 'BRITA',
      url: '/',
      imageUrl: '/wasser/w.jpg',
        
    },
    {
      index: '3', 
      name: 'spaqa iQ',  
      brand: 'spaqa',
      url: '/',
      imageUrl: '/wasser/w3.png',
       
    },
    {
      index: '4', 
      name: 'rhea COOL',  
      brand: 'rhea',
      url: '/',
      imageUrl: '/wasser/w2.jpg',
       
    },
    
  ];

export default wasser