import React from "react";
import {
  Button,
  Center,
  Flex,
  Heading,
  Image,
  Stack,
  Box,
  Grid,
  Text,
  useBreakpointValue,
  IconButton,
  Container,
  chakra,
  Divider,
  VStack,
  SimpleGrid,
  StackDivider,
  useColorModeValue,
  VisuallyHidden,
  List,
  ListItem,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  ListIcon,
  OrderedList,
  UnorderedList,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  ButtonGroup,
} from "@chakra-ui/react";
import { useRouter } from "next/router";
import Head from "next/head";
import { saveAs } from "file-saver";

import {
  CloseIcon,
  StarIcon,
  ChevronDownIcon,
  ChevronRightIcon,
} from "@chakra-ui/icons";

// Here we have used react-icons package for the icons
import { ArrowLeftIcon, ArrowRightIcon } from "@chakra-ui/icons";
// And react-slick as our Carousel Lib
import Slider from "react-slick";

import Jura from "../../mashcineCategory/jura";

import JuraZubehör from "../../../componenets/jura/Zubehor";

import UberService from "../../../componenets/UberService";

import We6slider from "../../../componenets/jura/productCarousel/We6slider.jsx";

import X3doc from "../../../componenets/jura/documents/X3doc.jsx";

const we6 = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>
          WE6 Professional || Kaffee-Service Berlin Peter Ganss GmbH
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        top={{ base: "90px", lg: 120 }}
        left={{ base: "10px", lg: 100 }}
        position={"absolute"}
      >
        <Breadcrumb fontWeight="medium" fontSize="sm">
          <BreadcrumbItem>
            <BreadcrumbLink href="/maschine">Büro Maschinen</BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem>
            <BreadcrumbLink href="/mashcineCategory/jura">
              Jura Kaffeevollautomaten
            </BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem isCurrentPage>
            <BreadcrumbLink href="#">WE6 Professional </BreadcrumbLink>
          </BreadcrumbItem>
        </Breadcrumb>
      </Box>
      <Container maxW={"7xl"}>
        <SimpleGrid
          columns={{ base: 1, lg: 2 }}
          spacing={{ base: 8, md: 10 }}
          py={{ base: 18, md: 24 }}
        >
          <Box
            my={10}
            borderRadius={10}
            boxShadow={"dark-lg"}
            mx={{ base: 5, lg: 0 }}
            w={{ base: "90%", lg: "80%" }}
          >
            <We6slider />
          </Box>
          <Stack spacing={{ base: 6, md: 10 }}>
            <Box as={"header"}>
              <Text
                textAlign={{ base: "center", lg: "left" }}
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: "2xl", sm: "4xl", lg: "5xl" }}
              >
                WE6 Professional
              </Text>
              <Text
                // eslint-disable-next-line react-hooks/rules-of-hooks
                color={useColorModeValue("gray.900", "gray.400")}
                textAlign={{ base: "center", lg: "left" }}
                fontWeight={300}
                fontSize={"2xl"}
              >
                Jura
              </Text>
            </Box>

            <Stack
              spacing={{ base: 4, sm: 6 }}
              direction={"column"}
              divider={
                <StackDivider
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  borderColor={useColorModeValue("gray.200", "gray.600")}
                />
              }
            >
              <VStack spacing={{ base: 4, sm: 6 }}>
                <Text
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  color={useColorModeValue("gray.500", "gray.400")}
                  fontSize={{ base: "xl", sm: "xl", lg: "2xl" }}
                  fontWeight={"300"}
                  textAlign={{ base: "center", lg: "left" }}
                >
                  Der Klassiker, Wo Kunden, Mitarbeitende und Gäste Kaffee
                  genießen, herrscht ein angenehmes Klima, denn Kaffee sorgt für
                  ein entspanntes, kommunikatives, produktives Umfeld. Er
                  beflügelt die Gedanken und mobilisiert kreative Kräfte. Kaffee
                  ist deshalb von keinem Arbeitsplatz wegzudenken. Die neue WE6
                  beherrscht virtuos die Klaviatur der Kaffeeklassiker von
                  Ristretto über Espresso bis hin zum Café crème.
                </Text>
              </VStack>
            </Stack>
          </Stack>
        </SimpleGrid>

        <Box>
          <Tabs isFitted variant="enclosed">
            <TabList mb="1em" flexWrap={"wrap"}>
              <Tab px={5}>Vorzüge</Tab>
              <Tab px={5}>Technische Übersicht</Tab>
              <Tab px={5}>Unseren Service</Tab>
              <Tab px={5}>Zubehör</Tab>
              <Tab px={5}>Dokumente</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <Grid
                  gridTemplateColumns={{
                    base: "repeat(1, 1fr)",
                    md: "repeat(2, 1fr)",
                    lg: "repeat(2, 1fr)",
                  }}
                  gap={0}
                  w={"100%"}
                >
                  <Image
                    p={6}
                    w={"800px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/we6/5.jpg"}
                  />
                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    12,2%* mehr Aroma sowie eine gleichbleibend hohe Qualität
                    des Mahlguts über die gesamte Lebensdauer zeichnen das
                    professionelle Aroma-Mahlwerk aus. Die perfektionierte
                    Mahlwerkgeometrie erreicht die optimale Mahlkurve. Das
                    heißt: Ein höherer Anteil an feinen Partikeln im Mahlgut
                    garantiert eine ideale Geschmacksentfaltung.
                  </Text>

                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    Weil die Anforderungen von Einsatzgebiet zu Einsatzgebiet
                    variieren, bietet die WE6 viele Möglichkeiten zur
                    Programmierung und Individualisierung. So lassen sich
                    Pulver- und Wassermenge ganz an die persönlichen Präferenzen
                    und das verwendete Geschirr anpassen. Ebenfalls können
                    bestimmte Kaffeespezialitäten durch die Sperrung anderer
                    präferiert werden. Auf Wunsch stehen auch verschiedene Modi
                    zur Verfügung, die das Ändern von Voreinstellungen oder
                    Tassenfüllmengen erst nach der Eingabe einer bestimmten
                    Tastenkombination erlaubt. Irrtümliche Fehlbedienung
                    ausgeschlossen.
                  </Text>
                  <Image
                    p={6}
                    w={"950px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/we6/6.jpg"}
                  />
                </Grid>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <List fontSize={"lg"} spacing={4}>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bis zu 8 individuell programmierbare Spezialitäten
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      500g Bohnenbehälter und 3 Liter Wassertank - Gerät immer
                      flexibel und mobil einsetzbar
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      30 Tassen pro Tag (365 Tage im Jahr)
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />2 Tassen
                      Kaffee oder Espresso gleichzeitig zubereiten
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Sechsstufige Aroma-Mahlwerk mahlt die Kaffeebohnen stets
                      frisch, schnell und gleichzeitig besonders aromaschonend
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Einfach bedienbar: Farbbildschirm mit 6 Tasten ergänzt um
                      eine akustische Rückmeldung
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Höhenverstellbarer Kaffeeauslauf 65 - 111mm und
                      Integrierte TÜV-zertifizierte Hygiene Reinigungsprogramme
                      garantieren minimalen Pflegeaufwand
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Überwachte Restwasserschale und Kaffeesatzbehälter für 25
                      Portionen
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      295x419x444mm (BxHxT), 10kg, 220-240V, 1450W
                    </ListItem>
                  </List>
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <UberService />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <JuraZubehör />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <X3doc />
                </Box>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </Container>
      <Jura />
    </div>
  );
};

export default we6;
