import React from "react";
import {
  Button,
  Center,
  Flex,
  Heading,
  Image,
  Stack,
  Box,
  Grid,
  Text,
  useBreakpointValue,
  IconButton,
  Container,
  chakra,
  Divider,
  VStack,
  SimpleGrid,
  StackDivider,
  useColorModeValue,
  VisuallyHidden,
  List,
  ListItem,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  ListIcon,
  OrderedList,
  UnorderedList,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  ButtonGroup,
} from "@chakra-ui/react";
import { useRouter } from "next/router";
import Head from "next/head";

import {
  CloseIcon,
  StarIcon,
  ChevronDownIcon,
  ChevronRightIcon,
} from "@chakra-ui/icons";

import Jura from "../../mashcineCategory/jura";

import JuraZubehör from "../../../componenets/jura/Zubehor";

import UberService from "../../../componenets/UberService";

import X10slider from "../../../componenets/jura/productCarousel/X10slider.jsx";

import X3doc from "../../../componenets/jura/documents/X3doc.jsx";

const x10 = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Giga X10 || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        top={{ base: "90px", lg: 120 }}
        left={{ base: "10px", lg: 100 }}
        position={"absolute"}
      >
        <Breadcrumb fontWeight="medium" fontSize="sm">
          <BreadcrumbItem>
            <BreadcrumbLink href="/maschine">Büro Maschinen</BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem>
            <BreadcrumbLink href="/mashcineCategory/jura">
              Jura Kaffeevollautomaten
            </BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem isCurrentPage>
            <BreadcrumbLink href="#">Giga X10 </BreadcrumbLink>
          </BreadcrumbItem>
        </Breadcrumb>
      </Box>
      <Container maxW={"7xl"}>
        <SimpleGrid
          columns={{ base: 1, lg: 2 }}
          spacing={{ base: 8, md: 10 }}
          py={{ base: 18, md: 24 }}
        >
          <Box
            my={10}
            borderRadius={10}
            boxShadow={"dark-lg"}
            mx={{ base: 5, lg: 0 }}
            w={{ base: "90%", lg: "80%" }}
          >
            <X10slider />
          </Box>
          <Stack spacing={{ base: 6, md: 10 }}>
            <Box as={"header"}>
              <Text
                textAlign={{ base: "center", lg: "left" }}
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: "2xl", sm: "4xl", lg: "5xl" }}
              >
                Giga X10
              </Text>
              <Text
                // eslint-disable-next-line react-hooks/rules-of-hooks
                color={useColorModeValue("gray.900", "gray.400")}
                textAlign={{ base: "center", lg: "left" }}
                fontWeight={300}
                fontSize={"2xl"}
              >
                Jura
              </Text>
            </Box>

            <Stack
              spacing={{ base: 4, sm: 6 }}
              direction={"column"}
              divider={
                <StackDivider
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  borderColor={useColorModeValue("gray.200", "gray.600")}
                />
              }
            >
              <VStack spacing={{ base: 4, sm: 6 }}>
                <Text
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  color={useColorModeValue("gray.500", "gray.400")}
                  fontSize={{ base: "xl", sm: "xl", lg: "2xl" }}
                  fontWeight={"300"}
                  textAlign={{ base: "center", lg: "left" }}
                >
                  Das Herzstück der neu entwickelten Jura X10 ist der Jura
                  Professional Aroma Grinder. Er ist nocheinmal ein ganzes Stück
                  leiser und extrahiert dabei noch weiter das Kaffeearoma. Über
                  den großen Touchscreen haben SIe Zugriff auf das gesamte
                  Spektrum an Kaffeespzialitäten mit und ohne Milch oder
                  Milchschaum. Dank des 1kg Bohnenbehälters und dem 5 Liter
                  Wassertank geht ihrem Kaffeeautomat nicht so schnell die Puste
                  aus. Mit dabei ist selbstverständliche auch die JURA-typische
                  TÜV-zertifizierte kinderleicht zu bedienender automatischen
                  Selbstreinigung für minimalen Pflegeaufwand.
                </Text>
              </VStack>
            </Stack>
          </Stack>
        </SimpleGrid>

        <Box>
          <Tabs isFitted variant="enclosed">
            <TabList mb="1em" flexWrap={"wrap"}>
              <Tab px={5}>Vorzüge</Tab>
              <Tab px={5}>Technische Übersicht</Tab>
              <Tab px={5}>Unseren Service</Tab>
              <Tab px={5}>Zubehör</Tab>
              <Tab px={5}>Dokumente</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <Grid
                  gridTemplateColumns={{
                    base: "repeat(1, 1fr)",
                    md: "repeat(2, 1fr)",
                    lg: "repeat(2, 1fr)",
                  }}
                  gap={0}
                  w={"100%"}
                >
                  <Image
                    p={6}
                    w={"800px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/x10/2.jpg"}
                  />
                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    Die X10 überzeugt mit Vielseitigkeit, Bedienerfreundlichkeit
                    und Individualität. Sie beherrscht 31 verschiedene
                    Spezialitäten, deckt damit das gesamte Spektrum der mit
                    Milch und Milchschaum verfeinerten Kaffees sowie die volle
                    Bandbreite von Schwarzkaffeespezialitäten ab. Für ein stets
                    perfektes Mahlergebnis und eine Aromasteigerung von 12,2%*
                    sorgt eine Top-Innovation: der Professional Aroma Grinder.
                    Dank der One-Touch-Lungo-Funktion weiß sie sogar mit Caffè
                    Barista und Lungo Barista zu begeistern. Die Bedienung über
                    das hochauflösende, 4,3 große, Touchscreen-Farbdisplay
                    gestaltet sich vollkommen intuitiv.
                  </Text>

                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    Als einzelner Vollautomat genauso, wie mit passenden
                    Peripheriegeräten wie Tassenwärmer, Abrechnungssystem, etc.
                    erweitert, auf Basis der GIGA X10 lässt sich für jedes
                    Einsatzgebiet die ideale Kaffee-Komplettlösung
                    konfigurieren. Bei Bedarf wächst sie auch bequem mit
                    steigenden Anforderungen mit.
                  </Text>
                  <Image
                    p={6}
                    w={"950px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/x10/3.jpg"}
                  />
                </Grid>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <List fontSize={"lg"} spacing={4}>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bis zu 31 individuell programmierbare Spezialitäten
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      1.000g Bohnenbehälterund 5 Liter Wassertank
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Automatischer Selbstreinigung für minimalen Pflegeaufwand
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      80 Tassen pro Tag (365 Tage im Jahr)
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bereiten Sie gleichzeitig 1-2 Tassen oder ein Kännchen
                      (360ml) 
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Einfach bedienbar: Individuell programmierbares
                      Touch-Display
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Neu entwickeltes sehr leises Mahlwerk: Jura Professional Aroma Grinder für 12,2% mehr Aroma
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Flexibel höhenverstellbarer Kombiauslauf 65 - 153mm
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Integrierte Reinigungsprogramme garantieren minimalen Pflegeaufwand
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      373x470x461mm (BxHxT), 14kg, 220-240V, 1450W
                    </ListItem>
                  </List>
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <UberService />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <JuraZubehör />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <X3doc />
                </Box>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </Container>
      <Jura />
    </div>
  );
};

export default x10;
