import React from 'react'
import {
    Button,
    Center,
    Flex,
    Heading,
    Image,
    Stack,
    Box,
    Grid,
    Text,
    useBreakpointValue, 
    IconButton, 
    Container, 
    chakra,     
    VStack,  
    SimpleGrid,
    StackDivider,
    useColorModeValue,
    VisuallyHidden,
    List,
    ListItem,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbSeparator, 
    ListIcon,
    OrderedList,
    UnorderedList,
    Tabs, TabList, TabPanels, Tab, TabPanel, 
  } from '@chakra-ui/react';
  import { useRouter } from 'next/router';
  import Head from 'next/head'; 

  import {
    MdCheckCircle,
    CloseIcon,
    ChevronDownIcon,
    ChevronRightIcon,
  } from '@chakra-ui/icons';



  // Here we have used react-icons package for the icons
import { ArrowLeftIcon, ArrowRightIcon } from '@chakra-ui/icons';
// And react-slick as our Carousel Lib
import Slider from 'react-slick';

import Jura from '../../mashcineCategory/jura';

// Settings for the slider
const settings = {
  dots: true,
  arrows: false,
  fade: true,
  infinite: true,
  autoplay: true,
  speed: 500,
  autoplaySpeed: 5000,
  slidesToShow: 1,
  slidesToScroll: 1,
};

function CaptionCarousel() {
    // As we have used custom buttons, we need a reference variable to
    // change the state
    const [slider, setSlider] = React.useState('Slider');
  
    // These are the breakpoints which changes the position of the
    // buttons as the screen size changes
    const top = useBreakpointValue({ base: '90%', md: '50%' });
    const side = useBreakpointValue({ base: '30%', md: '40px' });
  
    // This list contains all the data for carousels
    // This can be static or loaded from a server
    const cards = [
      { 
        image:
          '/jura/x3/1.jpg',
      },
      {
         
        image:
        '/jura/x3/2.jpg',
      },
      {
        
        image:
        '/jura/x3/3.jpg',
      },
      {
        
        image:
        '/jura/x3/4.jpg',
      },
      {
        
        image:
        '/jura/x3/5.jpg',
      },
      {
        
        image:
        '/jura/x3/6.jpg',
      },
    ];
  
    return (
      <Box
        position={'relative'}
        mt={0}
        height={'100%'}
        width={'100%'}
        overflow={'hidden'}>
        {/* CSS files for react-slick */}
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        {/* Left Icon */}
        <IconButton
          aria-label="left-arrow"
          variant="ghost"
          position="absolute"
          left={30}
          top={250}
          transform={'translate(0%, -50%)'}
          zIndex={2}
          onClick={() => slider?.slickPrev()}>
          <ArrowLeftIcon size="40px" />
        </IconButton>
        {/* Right Icon */}
        <IconButton
          aria-label="right-arrow"
          variant="ghost"
          position="absolute"
          right={30}
          top={250}
          transform={'translate(0%, -50%)'}
          zIndex={2}
          onClick={() => slider?.slickNext()}>
          <ArrowRightIcon size="40px" />
        </IconButton>
        {/* Slider */}
        <Slider {...settings} ref={(slider) => setSlider(slider)}>
          {cards.map((card, index) => (
            <Box
              key={index} 
              h={500}
              position="relative"
              backgroundPosition="center"
              backgroundRepeat="no-repeat"
              backgroundSize={'contain'}
              backgroundImage={`url(${card.image})`}>
             
            </Box>
          ))}
        </Slider>
      </Box>
    );
  }

const x3 = () => {

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter();
  
  return (
    <div> 

      <Head>
        <title>Giga X3 || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Box 
       top={170}
       left={100}
       position={'absolute'}
          >
          <Breadcrumb fontWeight='medium' fontSize='sm'> 

  <BreadcrumbItem>
    <BreadcrumbLink href='/maschine'>Büro Maschinen</BreadcrumbLink>
  </BreadcrumbItem>

  <BreadcrumbItem >
    <BreadcrumbLink href='/mashcineCategory/vollautomaten'>Jura Kaffeevollautomaten</BreadcrumbLink>
  </BreadcrumbItem>

  <BreadcrumbItem isCurrentPage>
    <BreadcrumbLink href='maschine/jurax3c'>Giga X3 </BreadcrumbLink>
  </BreadcrumbItem>
</Breadcrumb>

          </Box>
        <Container maxW={'7xl'}>

        
      <SimpleGrid
        columns={{ base: 1, lg: 2 }}
        spacing={{ base: 8, md: 10 }}
        py={{ base: 18, md: 24 }}>
        <Flex  
        my={10}
        borderRadius={10}
        boxShadow={'dark-lg'}
        w={'80%'} >
          <CaptionCarousel
            rounded={'md'}
            alt={'maschine image'} 
            fit={'contain'}
            align={'center'}
            w={'100%'}
            h={{ base: '100%', sm: '400px', lg: '100%' }}
          />
        </Flex>
        <Stack spacing={{ base: 6, md: 10 }}>
          <Box as={'header'}>
            <Heading
              lineHeight={1.1}
              fontWeight={600}
              fontSize={{ base: '2xl', sm: '4xl', lg: '5xl' }}>
              Giga X3
            </Heading>
            <Text
              // eslint-disable-next-line react-hooks/rules-of-hooks
              color={useColorModeValue('gray.900', 'gray.400')}
              fontWeight={300}
              fontSize={'2xl'}>
              Jura
            </Text>
          </Box>

          <Stack
            spacing={{ base: 4, sm: 6 }}
            direction={'column'}
            divider={
              <StackDivider
                // eslint-disable-next-line react-hooks/rules-of-hooks
                borderColor={useColorModeValue('gray.200', 'gray.600')}
              />
            }>
            <VStack spacing={{ base: 4, sm: 6 }}>
              <Text
                // eslint-disable-next-line react-hooks/rules-of-hooks
                color={useColorModeValue('gray.500', 'gray.400')}
                fontSize={'2xl'}
                fontWeight={'300'}>
                Wo Schwarzkaffeespezialitäten favorisiert, professionell Kännchenkaffee zubereitet 
                und heißes Wasser in zwei verschiedenen Temperaturstufen für Tee zur Verfügung gestellt 
                werden soll, spielt die Jura X6 ihre Stärken voll aus. Ihr klar verständliches Bedienkonzept 
                überzeugt besonders dort, wo sie von Personal oder von Gästen selbst bedient wird. Auch 
                die einfach zu bedienen Selbstreinigung kann voll überzeugen und hält nicht den Alltagsbetrieb auf.
              </Text>
               
            </VStack>
             
            
          </Stack>
 
        </Stack>
      </SimpleGrid>

<Box>
<Tabs isFitted variant='enclosed'>
  <TabList   mb='1em'>
    <Tab>Vorzüge</Tab>
    <Tab>Technische Übersicht</Tab>
    <Tab>Service</Tab> 
  </TabList>
  <TabPanels>
    <TabPanel>
      <Grid gridTemplateColumns={'repeat(2, 1fr)'} py={5} >
      <Image
            p={6}
            w={'800px'}
            alt={'Login Image'}
            objectFit={'contain'}
            src={'/jura/x3/4.jpg'}
          />
      <Text fontSize={20} p={30} textAlign={'center'} mt={'80px'} 
      >Ihr Einstieg in die Oberklasse
Die GIGA X8cGeneration2 ist eine Neuentwicklung auf Basis der langjährigen 
Erfahrung aus dem Hause Jura für die professionelle Kaffeeversorgung. Die 
einzigartiger Speed-Funktion bietet perfekten Kaffeegenuss in Rekordzeit - 
ideal bei maximaler Auslastung. Sehr belastbar für einen täglichen Bezug von 
täglich 200 Tassen höchsten Kaffeegenuss. Mit den 2 Farbvarianten Chrom und Schwarz 
passt sie sich perfekt in Ihre Küche ein.
   </Text>

   

   <Text fontSize={20} p={30}  textAlign={'center'} mt={'80px'} 
      >Ihr Einstieg in die Oberklasse
Die GIGA X8cGeneration2 ist eine Neuentwicklung auf Basis der langjährigen 
Erfahrung aus dem Hause Jura für die professionelle Kaffeeversorgung. Die 
einzigartiger Speed-Funktion bietet perfekten Kaffeegenuss in Rekordzeit - 
ideal bei maximaler Auslastung. Sehr belastbar für einen täglichen Bezug von 
täglich 200 Tassen höchsten Kaffeegenuss. Mit den 2 Farbvarianten Chrom und Schwarz 
passt sie sich perfekt in Ihre Küche ein.
   </Text>
   <Image
            p={6}
            w={'950px'}
            alt={'Login Image'}
            objectFit={'contain'}
            src={'/jura/x3/2.jpg'}
          />

    </Grid>
    </TabPanel>
    <TabPanel>
       <Box py={12} >
       <List spacing={3}>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Kaffeegenuss auf höchstem Niveau: Ristretto, Espresso, Café Crème, Cappuccino, Latte macchiato… bis zu 32 individuell programmierbare Spezialitäten
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Sehr schnelle Zubereitung: z.B. 2 Latte macciato in nur 86 sek.
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Hohe Kapazität: Festwasseranschluss und
2 x 650g Bohnenbehälter minimaler Aufwand beim Befülle
  </ListItem>
  {/* You can also use custom icons from react-icons */}
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    200 Tassen pro Tag (365 Tage im Jahr)
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Bereiten Sie gleichzeitig 1-2 Tassen oder ein Kännchen (360ml) zu
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Einfach bedienbar: Intuitiv bedienbarer und programmierbarer Touchscreen und akustische Rückmeldung
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Professionelle Kaffeezubereitung: zwei elektrisch verstellbare Profi-Keramikmahlwerke für schnelle, präzise, homogene, konstant gleichmäßige Mahlung, sowie zwei Heizsysteme, zwei Pumpen und zwei Fluidsysteme und variable Brühkammer mit 5 bis 16g
  </ListItem>
</List>
       </Box>
    </TabPanel>
  </TabPanels>
</Tabs>
</Box>

    </Container>
    <Jura/>
    </div>
  )
}

export default x3