import React from "react";
import {
  Button,
  Center,
  Flex,
  Heading,
  Image,
  Stack,
  Box,
  Grid,
  Text,
  useBreakpointValue,
  IconButton,
  Container,
  chakra,
  Divider,
  VStack,
  SimpleGrid,
  StackDivider,
  useColorModeValue,
  VisuallyHidden,
  List,
  ListItem,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  ListIcon,
  OrderedList,
  UnorderedList,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  ButtonGroup,
} from "@chakra-ui/react";
import { useRouter } from "next/router";
import Head from "next/head";
import { saveAs } from "file-saver";

import {
  CloseIcon,
  StarIcon,
  ChevronDownIcon,
  ChevronRightIcon,
} from "@chakra-ui/icons";

// Here we have used react-icons package for the icons
import { ArrowLeftIcon, ArrowRightIcon } from "@chakra-ui/icons";
// And react-slick as our Carousel Lib
import Slider from "react-slick";

import Jura from "../../mashcineCategory/jura";

import JuraZubehör from "../../../componenets/jura/Zubehor";

import UberService from "../../../componenets/UberService";

import X3slider from "../../../componenets/jura/productCarousel/X3slider.jsx";

import X3doc from "../../../componenets/jura/documents/x3doc.jsx"

const x3 = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter();
   

  return (
    <div>
      <Head>
        <title>Giga X3 || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        top={{ base: "90px", lg: 120 }}
        left={{ base: "10px", lg: 100 }}
        position={"absolute"}
      >
        <Breadcrumb fontWeight="medium" fontSize="sm">
          <BreadcrumbItem>
            <BreadcrumbLink href="/maschine">Büro Maschinen</BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem>
            <BreadcrumbLink href="/mashcineCategory/jura">
              Jura Kaffeevollautomaten
            </BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem isCurrentPage>
            <BreadcrumbLink href="#">Giga X3 </BreadcrumbLink>
          </BreadcrumbItem>
        </Breadcrumb>
      </Box>
      <Container maxW={"7xl"}>
        <SimpleGrid
          columns={{ base: 1, lg: 2 }}
          spacing={{ base: 8, md: 10 }}
          py={{ base: 18, md: 24 }}
        >
          <Box
            my={10}
            borderRadius={10}
            boxShadow={"dark-lg"}
            mx={{ base: 5, lg: 0 }}
            w={{ base: "90%", lg: "80%" }}
          >
            <X3slider />
          </Box>
          <Stack spacing={{ base: 6, md: 10 }}>
            <Box as={"header"}>
              <Text
                textAlign={{ base: "center", lg: "left" }}
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: "2xl", sm: "4xl", lg: "5xl" }}
              >
                Giga X3
              </Text>
              <Text
                // eslint-disable-next-line react-hooks/rules-of-hooks
                color={useColorModeValue("gray.900", "gray.400")}
                textAlign={{ base: "center", lg: "left" }}
                fontWeight={300}
                fontSize={"2xl"}
              >
                Jura
              </Text>
            </Box>

            <Stack
              spacing={{ base: 4, sm: 6 }}
              direction={"column"}
              divider={
                <StackDivider
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  borderColor={useColorModeValue("gray.200", "gray.600")}
                />
              }
            >
              <VStack spacing={{ base: 4, sm: 6 }}>
                <Text
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  color={useColorModeValue("gray.500", "gray.400")}
                  fontSize={{ base: "xl", sm: "xl", lg: "2xl" }}
                  fontWeight={"300"}
                  textAlign={{ base: "center", lg: "left" }}
                >
                  Mit der GIGA X3 beweist JURA eindrücklich Schweizer
                  Innovationskraft und Professionalität bis ins kleinste Detail.
                  Überall, wo Kapazitäten bis zu 150 Tassen an der Tagesordnung
                  sind, überzeugt sie mit Qualität, Funktionalität und
                  Zuverlässigkeit. Gepaart mit Höchstleistung in allen Belangen
                  resultiert ein Hightech-Vollautomat, der ideal auf die
                  Anforderungen von Großbüros, dem Frühstücks-, Seminar- und
                  Tagungsbereich sowie Selbstbedienungszonen zugeschnitten ist.
                </Text>
              </VStack>
            </Stack>
          </Stack>
        </SimpleGrid>

        <Box>
          <Tabs isFitted variant="enclosed">
            <TabList mb="1em" flexWrap={"wrap"}>
              <Tab px={5}>Vorzüge</Tab>
              <Tab px={5}>Technische Übersicht</Tab>
              <Tab px={5}>Unseren Service</Tab>
              <Tab px={5}>Zubehör</Tab>
              <Tab px={5}>Dokumente</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <Grid
                  gridTemplateColumns={{
                    base: "repeat(1, 1fr)",
                    md: "repeat(2, 1fr)",
                    lg: "repeat(2, 1fr)",
                  }}
                  gap={0}
                  w={"100%"}
                >
                  <Image
                    p={6}
                    w={"800px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/x3/4.jpg"}
                  />
                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    Die GIGA X3 hat’s in sich: Das
                    Hochleistungs-Keramikscheibenmahlwerk liefert zuverlässig
                    über Jahre eine präzise, konstant gleichmäßige Mahlung.
                    Dafür sorgt eine Top-Innovation: A.G.A. (Automatic Grinder
                    Adjustment) – die elektronisch gesteuerte, automatische
                    Nachjustierung. Der Puls-Extraktionsprozess (P.E.P.®)
                    optimiert die Extraktionszeit für kurze Spezialitäten und
                    CLARIS Pro Smart in Kombination mit dem Intelligent Water
                    System (I.W.S.) liefert perfekte Wasserqualität für puren
                    Geschmack.
                  </Text>

                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    Als einzelner Vollautomat genauso, wie mit passenden
                    Peripheriegeräten wie Tassenwärmer, Abrechnungssystem, etc.
                    erweitert, auf Basis der GIGA X3 lässt sich für jedes
                    Einsatzgebiet die ideale Kaffee-Komplettlösung
                    konfigurieren. Bei Bedarf wächst sie auch bequem mit
                    steigenden Anforderungen mit.
                  </Text>
                  <Image
                    p={6}
                    w={"950px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/x3/2.jpg"}
                  />
                </Grid>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <List fontSize={"lg"} spacing={4}>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bis zu 32 individuell programmierbare Spezialitäten
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Hohe Kapazität: 1 kg Bohnenbehälter minimaler Aufwand beim
                      Befüllen 5 Liter Wassertank Gerät immer flexibel und mobil
                      einsetzbar.
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      150 Tassen pro Tag (365 Tage im Jahr)
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bereiten Sie gleichzeitig 1-2 Tassen oder ein Kännchen
                      (360ml) dank der Bypass-Funktion in High-Speed zu
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Einfach bedienbar: Individuell programmierbares
                      Touch-Farbbildschirm
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Professionelle Kaffeezubereitung: Keramik-Mahlwerk für
                      schnelle, präzise, homogene, konstant gleichmäßige
                      Mahlung, <br /> sowie zwei Heizsysteme, zwei Pumpen und
                      zwei Fluidsysteme
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Verbesserte Reinigungsprogramme garantiert einen geringen
                      Pflegeaufwand
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      496x320x550mm (LxBxH), 19kg, 220-240V, 2300W
                    </ListItem>
                  </List>
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <UberService />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <JuraZubehör />
                </Box>
              </TabPanel>

              <TabPanel>
              <Box py={12}>
                  <X3doc />
                </Box>
                 
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </Container>
      <Jura />
    </div>
  );
};

export default x3;
