import React from "react";
import {
  Button,
  Center,
  Flex,
  Heading,
  Image,
  Stack,
  Box,
  Grid,
  Text,
  useBreakpointValue,
  IconButton,
  Container,
  chakra,
  Divider,
  VStack,
  SimpleGrid,
  StackDivider,
  useColorModeValue,
  VisuallyHidden,
  List,
  ListItem,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  ListIcon,
  OrderedList,
  UnorderedList,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  ButtonGroup,
} from "@chakra-ui/react";
import { useRouter } from "next/router";
import Head from "next/head";
import { saveAs } from "file-saver";

import {
  CloseIcon,
  StarIcon,
  ChevronDownIcon,
  ChevronRightIcon,
} from "@chakra-ui/icons";

import Jura from "../../mashcineCategory/jura";

import JuraZubehör from "../../../componenets/jura/Zubehor";

import UberService from "../../../componenets/UberService";

import X6slider from "../../../componenets/jura/productCarousel/X6slider.jsx";

import X3doc from "../../../componenets/jura/documents/X3doc.jsx";

const x6 = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Giga X3 || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        top={{ base: "90px", lg: 120 }}
        left={{ base: "10px", lg: 100 }}
        position={"absolute"}
      >
        <Breadcrumb fontWeight="medium" fontSize="sm">
          <BreadcrumbItem>
            <BreadcrumbLink href="/maschine">Büro Maschinen</BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem>
            <BreadcrumbLink href="/mashcineCategory/jura">
              Jura Kaffeevollautomaten
            </BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem isCurrentPage>
            <BreadcrumbLink href="#">Giga X6 </BreadcrumbLink>
          </BreadcrumbItem>
        </Breadcrumb>
      </Box>
      <Container maxW={"7xl"}>
        <SimpleGrid
          columns={{ base: 1, lg: 2 }}
          spacing={{ base: 8, md: 10 }}
          py={{ base: 18, md: 24 }}
        >
          <Box
            my={10}
            borderRadius={10}
            boxShadow={"dark-lg"}
            mx={{ base: 5, lg: 0 }}
            w={{ base: "90%", lg: "80%" }}
          >
            <X6slider />
          </Box>
          <Stack spacing={{ base: 6, md: 10 }}>
            <Box as={"header"}>
              <Text
                textAlign={{ base: "center", lg: "left" }}
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: "2xl", sm: "4xl", lg: "5xl" }}
              >
                Giga X6
              </Text>
              <Text
                // eslint-disable-next-line react-hooks/rules-of-hooks
                color={useColorModeValue("gray.900", "gray.400")}
                textAlign={{ base: "center", lg: "left" }}
                fontWeight={300}
                fontSize={"2xl"}
              >
                Jura
              </Text>
            </Box>

            <Stack
              spacing={{ base: 4, sm: 6 }}
              direction={"column"}
              divider={
                <StackDivider
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  borderColor={useColorModeValue("gray.200", "gray.600")}
                />
              }
            >
              <VStack spacing={{ base: 4, sm: 6 }}>
                <Text
                  // eslint-disable-next-line react-hooks/rules-of-hooks
                  color={useColorModeValue("gray.500", "gray.400")}
                  fontSize={{ base: "xl", sm: "xl", lg: "2xl" }}
                  fontWeight={"300"}
                  textAlign={{ base: "center", lg: "left" }}
                >
                  Wo Schwarzkaffeespezialitäten favorisiert, professionell
                  Kännchenkaffee zubereitet und heißes Wasser in zwei
                  verschiedenen Temperaturstufen für Tee zur Verfügung gestellt
                  werden soll, spielt die Jura X6 ihre Stärken voll aus. Ihr
                  klar verständliches Bedienkonzept überzeugt besonders dort, wo
                  sie von Personal oder von Gästen selbst bedient wird. Auch die
                  einfach zu bedienen Selbstreinigung kann voll überzeugen und
                  hält nicht den Alltagsbetrieb auf.
                </Text>
              </VStack>
            </Stack>
          </Stack>
        </SimpleGrid>

        <Box>
          <Tabs isFitted variant="enclosed">
            <TabList mb="1em" flexWrap={"wrap"}>
              <Tab px={5}>Vorzüge</Tab>
              <Tab px={5}>Technische Übersicht</Tab>
              <Tab px={5}>Unseren Service</Tab>
              <Tab px={5}>Zubehör</Tab>
              <Tab px={5}>Dokumente</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <Grid
                  gridTemplateColumns={{
                    base: "repeat(1, 1fr)",
                    md: "repeat(2, 1fr)",
                    lg: "repeat(2, 1fr)",
                  }}
                  gap={0}
                  w={"100%"}
                >
                  <Image
                    p={6}
                    w={"800px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/x6/4.jpg"}
                  />
                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    12,2%* mehr Aroma sowie eine gleichbleibend hohe Qualität
                    des Mahlguts über die gesamte Lebensdauer zeichnen das
                    professionelle Aroma-Mahlwerk aus. Die perfektionierte
                    Mahlwerkgeometrie erreicht die optimale Mahlkurve. Das
                    heißt: Ein höherer Anteil an feinen Partikeln im Mahlgut
                    garantiert eine ideale Geschmacksentfaltung. Der
                    Puls-Extraktionsprozess (P.E.P.®) optimiert die
                    Extraktionszeit für kurze Spezialitäten und zündet bei
                    Ristretto und Espresso ein geschmackliches Feuerwerk.
                  </Text>

                  <Text
                    fontSize={{ base: "lg", sm: "xl", lg: "xl" }}
                    p={{ base: 0, md: 30 }}
                    textAlign={"center"}
                    mt={{ base: "10px", lg: "80px" }}
                  >
                    Sämtliche Bedienelemente der X6 sind frontal angeordnet, auf
                    den ersten Blick klar erkennbar und mühelos zugänglich.
                    Sogar das Nachfüllen des Wassertanks und des Bohnenbehälters
                    ist von vorn möglich. Wassertank und Bohnenbehälter verfügen
                    serienmäßig über einen Verschlussmechanismus, über den sie
                    sich zum Schutz vor Fremdeinwirkung verriegeln lassen. Die
                    Restwasserschale und der Kaffeesatzbehälter sind ergonomisch
                    durchdacht gestaltet, mit nur einer Hand entfernbar und
                    dadurch sauber sowie schnell zu leeren.
                  </Text>
                  <Image
                    p={6}
                    w={"950px"}
                    alt={"Login Image"}
                    objectFit={"contain"}
                    src={"/jura/x6/2.jpg"}
                  />
                </Grid>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <List fontSize={"lg"} spacing={4}>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bis zu 12 individuell programmierbare Spezialitäten
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      500g Bohnenbehälter und 5 Liter Wassertank Gerät immer
                      flexibel und mobil einsetzbar
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      80 Tassen pro Tag (365 Tage im Jahr)
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Bereiten Sie gleichzeitig 1-2 Tassen oder ein Kännchen
                      (360ml) zu
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Einfach bedienbar: individuell programmierbarer 2,8 Zoll
                      TFT-Display
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Professionelle Kaffeezubereitung: Mehrstufiges Aroma
                      G3-Mahlwerke für schnelle, präzise Mahlung
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Flexibel höhenverstellbarer Kaffeeauslauf 65 - 153m
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      Integrierte Reinigungsprogramme garantieren minimalen
                      Pflegeaufwand
                    </ListItem>
                    <ListItem>
                      <ListIcon as={StarIcon} color="green.500" />
                      496x320x550mm (LxBxH), 19kg, 220-240V, 2300W
                    </ListItem>
                  </List>
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <UberService />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <JuraZubehör />
                </Box>
              </TabPanel>

              <TabPanel>
                <Box py={12}>
                  <X3doc />
                </Box>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </Container>
      <Jura />
    </div>
  );
};

export default x6;
