import { Container, Heading, Text } from '@chakra-ui/react'
import React from 'react'
import Head from 'next/head'
import KaffeeServiceGrid from '../componenets/KaffeeServiceGrid'
import AboutSection from '../componenets/AboutSection.tsx'
import KundenGrid from '../componenets/KundenGrid.tsx'

const about = () => {
  return (
    <div>
     <Head>
        <title>Über KSB || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         
      
      <AboutSection/>
      <KundenGrid/>
       
    </div>
  )
}

export default about