import React from 'react'
import { getOrderForm } from '../services'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../componenets/Hero'
import NavBar from '../componenets/NavBar.tsx'
import {
    FormControl,
    FormLabel,
    FormErrorMessage,
    FormHelperText,
    Input,
    RadioGroup,
    HStack,
    Radio,
    Textarea,
    Text,
    Button ,Checkbox, CheckboxGroup 
  } from '@chakra-ui/react'
  import { useForm, FormContext, useFormContext  } from "react-hook-form";
import Form from '../componenets/OrderForm'


const cart = ({OrderForm}) => {

    console.log(OrderForm)

    let [Note, setNote] = React.useState('')

  let handleInputChange = (e) => {
    let note = e.target.value
    setNote(note)
  }

  const { handleSubmit, ...methods } = useForm();

  const onSubmit = (values) => console.log(`Email input value: ${Note}`);

  const  register  = useFormContext();



  return (
    <div className={styles.container}>
      <Head>
        <title>Cart || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar/>
        
        <form onSubmit={handleSubmit(onSubmit)} >

        {OrderForm.map((OrderForm, index) => (
            <>

<FormControl isRequired key={index}>
<FormLabel htmlFor='text'  > {OrderForm.node.orderInput.slice(0,1).map((orderInput) => ( <> {orderInput.label} </>  ))} </FormLabel>
<Input id='text' type='text' ref={register} />
</FormControl>

<FormControl isRequired key={index} >
  <FormLabel htmlFor='email'>{OrderForm.node.orderInput.slice(1,2).map((orderInput) => ( <> {orderInput.label} </>  ))}</FormLabel>
  <Input id='email' type='email' />
</FormControl>



{OrderForm.node.orderSelects.map((orderSelects) => ( 
<> 
<FormControl key={''} as='fieldset'>
  <FormLabel as='legend'>
       {orderSelects.name} 
  </FormLabel>
  <RadioGroup key={''}>
    <HStack spacing='24px'>
    
    {orderSelects.orderOption.map((orderOption) => ( 
    <> 
    <Radio key={''} value={orderOption.value}> {orderOption.value} </Radio>
    </>
    ))}
   
    </HStack>
  </RadioGroup>
  
</FormControl> 
</>  ))}

{OrderForm.node.orderCheckbox.map((orderCheckbox) => ( 
<> 

    
    <Checkbox  > {orderCheckbox.label} </Checkbox>
    
   
</>  ))}

<>

<Text mb='8px'> {OrderForm.node.orderTextarea.name}</Text>
      <Textarea
      ref={register}
      id={OrderForm.node.orderTextarea.name}
      htmlFor={OrderForm.node.orderTextarea.name}
        value={Note}
        onChange={handleInputChange}
        placeholder={OrderForm.node.orderTextarea.placeholder}
        size='sm'
      />

      
    </>

</>
        

        ))}

<Button type='submit' onClick={handleSubmit}  >Submit-Order</Button>



        

        </form>
        
      </main>

      <footer className={styles.footer}>
      Kaffee-Service Berlin Peter Ganss GmbH
      </footer>
    </div>
  )
}

export default cart

// Fetch data at build time
export async function getStaticProps() {
    const  OrderForm = (await getOrderForm()) || [];
    return {
      props: {  OrderForm },
    };
  }