import { Container, Heading, Text, Stack, 
    Divider,
    Box } from '@chakra-ui/react'
import React from 'react'
import Head from 'next/head';
import Form from '../componenets/Form.tsx'

const about = () => {
  return (
    <div>
        <Head>
        <title>Kontakt || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
      boxShadow={'dark-lg'}
      pb={20}
      my={20}
      maxW={'5xl'}>
        <Stack
          as={Box}
          textAlign={'center'}
          mb={-10}
          spacing={{ base: 8, md: 14 }}
          py={{ base: 20, md: 16 }}>
          <Heading
            fontWeight={600}
            fontSize={{ base: '2xl', sm: '4xl', md: '5xl' }}
            lineHeight={'110%'}>
           Hotline & Kundendienst
 
          </Heading>
          <Text color={'gray.500'}>
          Gern laden wir Sie auf einen Kaffee oder Espresso ein! Wir beraten Sie kompetent und freundlich. Gemeinsam finden wir auch für Sie den richtigen Service für Ihre Kaffeeversorgung am Arbeitsplatz.
          </Text>
          
        </Stack>
        <Stack 
        fontSize={'2xl'} 
        direction='row' h='150px'  p={4}>
        <Divider orientation='vertical' p={10} />
        <Text>Kundenhotline <br/> (030) 688 11 49 - 0 <br/>
        Email - info@kaffee-service-espresso.de
        <br/>Fax - 030 - 688 11 49 - 29  </Text>
        
         
        <Divider orientation='vertical' p={10}  />
        <Text>Crellestr. 29-30, 10827 Berlin <br/>  
        Bürozeit: Mo. - Fr.<br/> von 8:00 - 17 Uhr</Text>
         
        </Stack>
      </Container>

      <Form/>
    </div>
  )
}

export default about