import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../componenets/Hero'
import NavBar from '../componenets/NavBar.tsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar/>
        <Hero/>
      </main>

      <footer className={styles.footer}>
      Kaffee-Service Berlin Peter Ganss GmbH
      </footer>
    </div>
  )
}
