import React from 'react'
import { ReactNode } from 'react';
import Head from 'next/head';
import {
  Box,
  Heading,
  Container,
  Text,
  Button,
  Stack,
  Icon,
  Flex,
  SimpleGrid,
  useColorModeValue,
  createIcon,
  Center,
} from '@chakra-ui/react';

import StatGrid from '../componenets/StatGrid';
import Form from '../componenets/Form.tsx'


const Arrow = createIcon({
    displayName: 'Arrow',
    viewBox: '0 0 72 24',
    path: (
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0.600904 7.08166C0.764293 6.8879 1.01492 6.79004 1.26654 6.82177C2.83216 7.01918 5.20326 7.24581 7.54543 7.23964C9.92491 7.23338 12.1351 6.98464 13.4704 6.32142C13.84 6.13785 14.2885 6.28805 14.4722 6.65692C14.6559 7.02578 14.5052 7.47362 14.1356 7.6572C12.4625 8.48822 9.94063 8.72541 7.54852 8.7317C5.67514 8.73663 3.79547 8.5985 2.29921 8.44247C2.80955 9.59638 3.50943 10.6396 4.24665 11.7384C4.39435 11.9585 4.54354 12.1809 4.69301 12.4068C5.79543 14.0733 6.88128 15.8995 7.1179 18.2636C7.15893 18.6735 6.85928 19.0393 6.4486 19.0805C6.03792 19.1217 5.67174 18.8227 5.6307 18.4128C5.43271 16.4346 4.52957 14.868 3.4457 13.2296C3.3058 13.0181 3.16221 12.8046 3.01684 12.5885C2.05899 11.1646 1.02372 9.62564 0.457909 7.78069C0.383671 7.53862 0.437515 7.27541 0.600904 7.08166ZM5.52039 10.2248C5.77662 9.90161 6.24663 9.84687 6.57018 10.1025C16.4834 17.9344 29.9158 22.4064 42.0781 21.4773C54.1988 20.5514 65.0339 14.2748 69.9746 0.584299C70.1145 0.196597 70.5427 -0.0046455 70.931 0.134813C71.3193 0.274276 71.5206 0.70162 71.3807 1.08932C66.2105 15.4159 54.8056 22.0014 42.1913 22.965C29.6185 23.9254 15.8207 19.3142 5.64226 11.2727C5.31871 11.0171 5.26415 10.5479 5.52039 10.2248Z"
        fill="currentColor"
      />
    ),
  });


  const Testimonial = ({ children }: { children: ReactNode }) => {
    return <Box>{children}</Box>;
  };
  
  const TestimonialContent = ({ children }: { children: ReactNode }) => {
    return (
      <Center> 
      <Stack
        bg={useColorModeValue('white', 'gray.800')}
        boxShadow={'dark-lg'}
        opacity={0.9} 
        w={{ base: '100%', md: '80%', lg: '100%' }}
        p={8}
        rounded={'xl'}
        align={'center'}
        pos={'relative'}
         >
        {children}
      </Stack>
      </Center>
    );
  };
  
  const TestimonialHeading = ({ children }: { children: ReactNode }) => {
    return (
      <Heading 
      color={'green.400'}
      fontSize={{ base: 'xl', sm: '4xl', md: '3xl' }}>
        {children}
      </Heading>
    );
  };
  
  const TestimonialText = ({ children }: { children: ReactNode }) => {
    return (
      <Text
        textAlign={'center'}
        color={useColorModeValue('gray.600', 'gray.400')}
        fontSize={{ base: 'lg', sm: '2xl', md: '2xl' }}>
        {children}
      </Text>
    );
  };
  

const service = () => {
  return (
    <div>
        <Head>
        <title>Eigenschaften || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <Container maxW={'3xl'}>
        <Stack
          as={Box}
          textAlign={'center'}
          mb={-10}
          spacing={{ base: 8, md: 14 }}
          py={{ base: 20, md: 16 }}>
          <Heading
            fontWeight={600}
            fontSize={{ base: '2xl', sm: '4xl', md: '5xl' }}
            lineHeight={'110%'}>
            Kaffee und Kaffeeautomaten mit FULLSERVICE  <br />
            <Text as={'span'} color={'green.400'}>
            mieten leasen oder kaufen
            </Text>
          </Heading>
          <Text color={'gray.500'}>
          Lassen Sie sich von unserem Service überzeugen und genießen Sie ganz einfach und bequem Kaffee in bester Qualität in Ihrem Büro, in der Praxis, der Werkstatt oder tageweise auch auf Messe und am Filmset. Unser ganzes Team arbeitet daran Ihnen den besten Service zu guten Preisen zu bieten.
          </Text>
          <Stack
            direction={'column'}
            spacing={3}
            align={'center'}
            alignSelf={'center'}
            position={'relative'}>
            <Button
              colorScheme={'green'}
              bg={'green.400'}
              rounded={'full'}
              px={6}
              _hover={{
                bg: 'green.500',
              }}>
              Kontakt
            </Button>
             
            <Box>
              <Icon
                as={Arrow}
                color={useColorModeValue('gray.800', 'gray.300')}
                w={71}
                position={'absolute'}
                right={-71}
                top={'10px'}
              />
              <Text
                fontSize={'lg'}
                fontFamily={'Caveat'}
                position={'absolute'}
                right={'-135px'}
                top={'-18px'}
                transform={'rotate(10deg)'}>
                kundenspezifische Angebote
              </Text>
            </Box>
          </Stack>
        </Stack>
      </Container>
      <StatGrid/>

       
      <Center
      px={{ base: 5, md: 300 , lg: 300 }}
      
      w={{ base: '100%', md: '80%', lg: '100%' }}
      >
      <Stack 
      spacing={0} align={'center'}>
          <Heading 
          textAlign={'center'}
          pb={16}
          fontSize={{ base: 'xl', sm: '4xl', md: '4xl' }} >Ihr persönlicher Büro-Kaffee-Service in Berlin und Umgebung bietet:</Heading>
          
       
        <SimpleGrid
          columns={{ base: 1, lg: 2 }}
          spacing={{ base: 10, md: 4, lg: 10 }}>
          <Testimonial>
            <TestimonialContent>
              <TestimonialHeading>Sofortige Bearbeitung</TestimonialHeading>
              <TestimonialText>
              Ihre Bestellungen, Fragen und Wünsche bearbeiten wir umgehend und 
              finden die passende Lösung.Flexibilität zeichnet uns aus! Wir erfüllen 
              auch gerne individuelle Wünsche.
              </TestimonialText>
            </TestimonialContent>
            
          </Testimonial>
          <Testimonial>
            <TestimonialContent>
              <TestimonialHeading>Kundenbetreuung</TestimonialHeading>
              <TestimonialText>
              Wir helfen Ihnen bei der richtigen Kaffeewahl für Ihren Einsatz: ob 
              Filterkaffee, Espresso-Pads oder ganze Bohnen im Vollautomat.Wir rufen Sie in regelmäßigen 
              Abständen an und sorgen dafür, dass Sie Ihre Kaffeebestellung nicht versäumen können.

              </TestimonialText>
            </TestimonialContent>
            
          </Testimonial>
          <Testimonial>
            <TestimonialContent>
              <TestimonialHeading>Weniger Aufwand</TestimonialHeading>
              <TestimonialText>
              Sie wollen so wenig Aufwand wie möglich? Unsere Techniker installieren 
              Ihnen einen Festwasseranschluss, Kaffeesatzabwurf und Restwasserablaufset.
              Um die Installation, Programmierung, sowie regelmäßige Wartung, Überprüfung und Entkalkung der Geräte brauchen Sie sich nicht zu kümmern – das übernehmen wir gern für Sie.
              </TestimonialText>
            </TestimonialContent>
             
          </Testimonial>
          <Testimonial>
            <TestimonialContent>
              <TestimonialHeading>Mehr Wahlmöglichkeiten</TestimonialHeading>
              <TestimonialText>
              Welche Kaffeesorte passt am besten zu Ihnen? Sie haben die Wahl aus unserem
               umfangreichem Angebot aus echten italienischen Kaffeebohnen, feinem Filterkaffee und italienischen Kaffeepads - wir kennen und prüfen unsere Sorten genau und bieten Ihnen die Möglichkeit zu probieren, welcher Kaffee Ihren Ansprüchen entspricht.
              </TestimonialText>
            </TestimonialContent>
             
          </Testimonial>

          <Testimonial >
            <TestimonialContent>
              <TestimonialHeading>Technische Schwierigkeiten? </TestimonialHeading>
              <TestimonialText>
              Kein Problem! Rufen Sie uns an – die meisten Probleme lassen sich einfach und schnell am Telefon klären. Sollte dies nicht gelingen, kommt noch am selben Werktag einer unserer Techniker bei Ihnen vorbei. Falls notwendig tauscht er das Gerät aus. Ihr defektes Gerät wird in unserer Werkstatt fachmännisch und schnell repariert.
Unsere Techniker besuchen regelmäßig Schulungen um immer auf dem aktuellsten Stand zu sein.
              </TestimonialText>
            </TestimonialContent>
             
          </Testimonial>

          <Testimonial>
            <TestimonialContent>
              <TestimonialHeading>Mehr Wahlmöglichkeiten</TestimonialHeading>
              <TestimonialText>
              Welche Kaffeesorte passt am besten zu Ihnen? Sie haben die Wahl aus unserem
               umfangreichem Angebot aus echten italienischen Kaffeebohnen, feinem Filterkaffee und italienischen Kaffeepads - wir kennen und prüfen unsere Sorten genau und bieten Ihnen die Möglichkeit zu probieren, welcher Kaffee Ihren Ansprüchen entspricht.
              </TestimonialText>
            </TestimonialContent>
             
          </Testimonial>

        </SimpleGrid>
        </Stack>
      </Center>
   
    <Form/>

    </div>
  )
}

export default service