import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Hero from '../componenets/Hero'
import NavBar from '../componenets/NavBar.tsx'
import { Heading, Text, Box, Image,Link,
  Center,
  Grid,
 
} from '@chakra-ui/react'
import Categories from '../componenets/Categories'
import SideCategories from '../componenets/SideCategories'
import { getCategories } from '../services'
import { useRouter } from 'next/router'

 function Shop({categories}) {

    const router = useRouter();
   
  return (
    <div >
      <Head>
        <title>Shop || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <SideCategories  />
        
        <Box
         width={{ base: '90%', md: '80%', lg: '80%' }}
        my={'90px'}
        px={{ base: 10, md: 20, lg: 20 }}
        pb={{ base: 10, md: 10, lg: 20 }}
        borderRadius={10}
        boxShadow={'dark-lg'} > 
      
       <Text 
       textAlign={'center'}
       fontSize={{ base: '3xl', md: '3xl', lg: '5xl' }}
       pb={10}
       pt={5}
       >Nach Kategorien durchsuchen...</Text>

        <Center >
          <Grid
          templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(3, 1fr)', lg: 'repeat(4, 1fr)' }} gap={4} w={'100%'} 
          >

        {categories.map((categories, index) => (
           
             

       <Box
  
       key={categories.node.slug}
       boxShadow={'dark-lg'}
        backgroundImage={categories.node.image.url}
        backgroundSize='cover'
        as='button'
        my={{ base: 2, md: 10, lg: 10 }}
        h={250}
        w={250}
        borderRadius={10}
        onClick={async () => { 
          router.push(`/category/${categories.node.slug}`);

          }}
        >
         
         
        <Text
        key={categories.node.slug}
        textAlign={'center'}
        backgroundColor={'white'}
        opacity={'0.9'}
        fontSize={'3xl'}
        fontWeight={'semibold'}
        my={2}
        borderRadius={5}
        >{categories.node.name}</Text>
          
        </Box>
         
            ))}
            </Grid>
        </Center>
    
    </Box>
     
      </main>

       
    </div>
  )
}


// Fetch data at build time
export async function getStaticProps() {
    const  categories = (await getCategories()) || [];
    return {
      props: {  categories },
    };
  }



  export default Shop;

