import Head from 'next/head'

import styles from '../../styles/Home.module.css'

import NavBar from '../../componenets/NavBar.tsx'

import {
    Box,
    chakra,
    Container,
    Stack,
    Text,
    Image,
    Flex,
    VStack,
    Button,
    Heading,
    SimpleGrid,
    StackDivider,
    useColorModeValue,
    VisuallyHidden,
    List,
    ListItem,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbSeparator, 
    Tabs, TabList, TabPanels, Tab, TabPanel, 
    
   
    ListIcon,
    OrderedList,
    UnorderedList,
    Grid,
  } from '@chakra-ui/react';

  import {
    MdCheckCircle,
    CloseIcon,
    ChevronDownIcon,
    ChevronRightIcon,
  } from '@chakra-ui/icons';

import { getMaschineDetails, getMashcinen } from '../../services/index'
import SideCategories from '../../componenets/SideCategories'
import ProductSlider from '../../componenets/ProductSlider'



export default function MaschinePage({maschine}) {

    

  return (
    <div >
      <Head>
        <title>Shop || Kaffee-Service Berlin Peter Ganss GmbH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
   
       <SideCategories/> 
       <Box 
       top={170}
       left={100}
       position={'absolute'}
          >
          <Breadcrumb fontWeight='medium' fontSize='sm'>
  <BreadcrumbItem>
    <BreadcrumbLink href='/'>Home</BreadcrumbLink>
  </BreadcrumbItem>

  <BreadcrumbItem>
    <BreadcrumbLink href='/maschine'>Maschinen/Zubehör</BreadcrumbLink>
  </BreadcrumbItem>

  <BreadcrumbItem >
    <BreadcrumbLink href='/mashcineCategory/vollautomaten'>Kaffeevollautomaten</BreadcrumbLink>
  </BreadcrumbItem>

  <BreadcrumbItem isCurrentPage>
    <BreadcrumbLink href='maschine/jurax3c'>Jura Giga x3c Professional</BreadcrumbLink>
  </BreadcrumbItem>
</Breadcrumb>

          </Box>
        <Container maxW={'7xl'}>

        
      <SimpleGrid
        columns={{ base: 1, lg: 2 }}
        spacing={{ base: 8, md: 10 }}
        py={{ base: 18, md: 24 }}>
        <Flex w={'100%'} >
          <ProductSlider
            rounded={'md'}
            alt={'maschine image'} 
            fit={'contain'}
            align={'center'}
            w={'100%'}
            h={{ base: '100%', sm: '400px', lg: '100%' }}
          />
        </Flex>
        <Stack spacing={{ base: 6, md: 10 }}>
          <Box as={'header'}>
            <Heading
              lineHeight={1.1}
              fontWeight={600}
              fontSize={{ base: '2xl', sm: '4xl', lg: '5xl' }}>
              {maschine.title}
            </Heading>
            <Text
              color={useColorModeValue('gray.900', 'gray.400')}
              fontWeight={300}
              fontSize={'2xl'}>
              {maschine.mashinenCategory.name}
            </Text>
          </Box>

          <Stack
            spacing={{ base: 4, sm: 6 }}
            direction={'column'}
            divider={
              <StackDivider
                borderColor={useColorModeValue('gray.200', 'gray.600')}
              />
            }>
            <VStack spacing={{ base: 4, sm: 6 }}>
              <Text
                color={useColorModeValue('gray.500', 'gray.400')}
                fontSize={'2xl'}
                fontWeight={'300'}>
                {maschine.excerpt}
              </Text>
               
            </VStack>
             
            
          </Stack>
 
        </Stack>
      </SimpleGrid>

<Box>
<Tabs isFitted variant='enclosed'>
  <TabList   mb='1em'>
    <Tab>Vorzüge</Tab>
    <Tab>Technische Übersicht</Tab>
    <Tab>Service</Tab> 
  </TabList>
  <TabPanels>
    <TabPanel>
      <Grid gridTemplateColumns={'repeat(2, 1fr)'} py={5} >
      <Image
            p={6}
            w={'500px'}
            alt={'Login Image'}
            objectFit={'cover'}
            src={'/jurax3c/jm4.jpg'}
          />
      <Text textAlign={'center'} mt={'80px'} 
      >Ihr Einstieg in die Oberklasse
Die GIGA X8cGeneration2 ist eine Neuentwicklung auf Basis der langjährigen 
Erfahrung aus dem Hause Jura für die professionelle Kaffeeversorgung. Die 
einzigartiger Speed-Funktion bietet perfekten Kaffeegenuss in Rekordzeit - 
ideal bei maximaler Auslastung. Sehr belastbar für einen täglichen Bezug von 
täglich 200 Tassen höchsten Kaffeegenuss. Mit den 2 Farbvarianten Chrom und Schwarz 
passt sie sich perfekt in Ihre Küche ein.
   </Text>

   <Text textAlign={'center'} mt={'80px'} 
      >Ihr Einstieg in die Oberklasse
Die GIGA X8cGeneration2 ist eine Neuentwicklung auf Basis der langjährigen 
Erfahrung aus dem Hause Jura für die professionelle Kaffeeversorgung. Die 
einzigartiger Speed-Funktion bietet perfekten Kaffeegenuss in Rekordzeit - 
ideal bei maximaler Auslastung. Sehr belastbar für einen täglichen Bezug von 
täglich 200 Tassen höchsten Kaffeegenuss. Mit den 2 Farbvarianten Chrom und Schwarz 
passt sie sich perfekt in Ihre Küche ein.
   </Text>
 

    </Grid>
    </TabPanel>
    <TabPanel>
       <Box py={12} >
       <List spacing={3}>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Kaffeegenuss auf höchstem Niveau: Ristretto, Espresso, Café Crème, Cappuccino, Latte macchiato… bis zu 32 individuell programmierbare Spezialitäten
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Sehr schnelle Zubereitung: z.B. 2 Latte macciato in nur 86 sek.
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Hohe Kapazität: Festwasseranschluss und
2 x 650g Bohnenbehälter minimaler Aufwand beim Befülle
  </ListItem>
  {/* You can also use custom icons from react-icons */}
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    200 Tassen pro Tag (365 Tage im Jahr)
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Bereiten Sie gleichzeitig 1-2 Tassen oder ein Kännchen (360ml) zu
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Einfach bedienbar: Intuitiv bedienbarer und programmierbarer Touchscreen und akustische Rückmeldung
  </ListItem>
  <ListItem>
    <ListIcon as={MdCheckCircle} color='green.500' />
    Professionelle Kaffeezubereitung: zwei elektrisch verstellbare Profi-Keramikmahlwerke für schnelle, präzise, homogene, konstant gleichmäßige Mahlung, sowie zwei Heizsysteme, zwei Pumpen und zwei Fluidsysteme und variable Brühkammer mit 5 bis 16g
  </ListItem>
</List>
       </Box>
    </TabPanel>
  </TabPanels>
</Tabs>
</Box>

    </Container>
      </main>

      
    </div>
  )
}


// Fetch data at build time
export async function getStaticProps({ params }) {
    const data = await getMaschineDetails(params.slug);
  
    return {
      props: { maschine: data },
    };
  }

  export async function getStaticPaths() {
    const maschinen = await getMashcinen();
    return {
      paths: maschinen.map(({ node: { slug } }) => ({ params: { slug } })),
      fallback: false,
    };
  }  

 